package com.db.dbworld.app.tally.mapper;

import com.db.dbworld.app.tally.dto.*;
import com.db.dbworld.app.tally.entity.*;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.math.BigDecimal;
import java.util.List;

/**
 * Entity-to-DTO mapping for db-tally, generated by MapStruct at compile time.
 *
 * <p>An interface rather than a hand-written component on purpose. These mappings are almost
 * entirely name-for-name, and writing them out by hand means a constructor call with a dozen
 * positional arguments — where transposing two adjacent {@code String} parameters compiles
 * cleanly and silently swaps two people's names, or a {@code from} and a {@code to}. Generating
 * them removes that class of bug outright, and a field added to an entity and its DTO needs no
 * edit here at all.
 *
 * <p>The values that are <em>not</em> on the entity — balances, counts, resolved display names —
 * arrive as extra method parameters. MapStruct matches those by name against the target record's
 * components, so they are as checked as the rest.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface TallyMapper {

    /* ============================== members ============================== */

    /**
     * @param balance the member's net position, which lives in the ledger rather than on the
     *                member row and so cannot be derived from {@code member} alone
     */
    TallyMemberDto toMemberDto(TallyGroupMemberEntity member, BigDecimal balance);

    /* ============================== groups ============================== */

    TallyGroupDetailDto toGroupDetail(TallyGroupEntity group, List<TallyMemberDto> members,
                                      String myMemberId);

    TallyGroupSummaryDto toGroupSummary(TallyGroupEntity group, int memberCount, BigDecimal myBalance);

    /* ============================== expenses ============================== */

    TallyExpensePayerDto toPayerDto(TallyExpensePayerEntity payer);

    TallyExpenseShareDto toShareDto(TallyExpenseShareEntity share);

    List<TallyExpensePayerDto> toPayerDtos(List<TallyExpensePayerEntity> payers);

    List<TallyExpenseShareDto> toShareDtos(List<TallyExpenseShareEntity> shares);

    TallyExpenseDto toExpenseDto(TallyExpenseEntity expense,
                                 List<TallyExpensePayerDto> payers,
                                 List<TallyExpenseShareDto> shares);

    /* ============================== settlements ============================== */

    TallySettlementDto toSettlementDto(TallySettlementEntity settlement);

    List<TallySettlementDto> toSettlementDtos(List<TallySettlementEntity> settlements);

    /* ============================== settle-up ============================== */

    /**
     * A suggested transfer, with both people's names resolved.
     *
     * <p>The names are looked up unfiltered, so somebody who has left still reads as a person
     * rather than an id — they can be owed money right up until the moment they are removed,
     * and removal is what requires the balance to be zero.
     */
    @Mapping(target = "fromMemberId", source = "fromMemberId")
    @Mapping(target = "toMemberId", source = "toMemberId")
    SettleUpTransferDto toTransferDto(String fromMemberId, String fromMemberName,
                                      String toMemberId, String toMemberName,
                                      BigDecimal amount);
}
