spring:
  profiles: local

app:
  paths:
    base: D:/home/dbworld_admin/ext_hdisk/dbworld
    data: D:/home/dbworld_admin/ext_hdisk/dbworld
    stream: D:/Bhavya/Videos
    symlink: D:/Bhavya/video-symlink
    integration: D:/Bhavya/ProcessedVideos
    external-videos: /home/dbworld_admin/ext_hdisk_1/videos

  tools:
    seven-zip: C:/Program Files/7-Zip/7z.exe
    mediainfo: D:/Bhavya/Downloads/Compressed/MediaInfo_CLI_24.12_Windows_x64/mediainfo

server:
  port: ${SERVER_PORT:9000}

cors:
  allowed-origins: https://dn-world.in

springdoc:
  swagger-ui:
    enabled: true



#https://api.themoviedb.org/3/movie/${tmdbId}?api_key=${TMDB_API_KEY}&append_to_response=videos
#https://api.themoviedb.org/3/movie/721048?api_key=${TMDB_API_KEY}&append_to_response=videos
#https://api.themoviedb.org/3/tv/123377?api_key=${TMDB_API_KEY}&append_to_response=videos,images,credits
#https://api.themoviedb.org/3/tv/${tmdbId}?api_key=${TMDB_API_KEY}&append_to_response=videos


#https://api.themoviedb.org/3/movie/721048/watch/providers?api_key=${TMDB_API_KEY}
#https://api.themoviedb.org/3/tv/123377/watch/providers?api_key=${TMDB_API_KEY}
#https://api.themoviedb.org/3/search/tv?api_key=TMDB_API_KEY&query=SERACH_TEXT&year=YEAR