# Server Config
Server:
  port: 9090
  jetty:
    idle-timeout: 60000 # 60 seconds

#MySQL Database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbworld_admin
    password: BD@pi#2024
    url: jdbc:mysql://localhost:3306/db_world?createDatabaseIfNotExist=true&jdbcCompliantTruncation=false
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    livereload:
      enable: false
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    enable-complex-map-key-serialization: true
  servlet:
    multipart:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

#Security
jwt:
  token:
    validity: 36000000  # validity in millisecond 10*60*60*1000 ~ 10hour
    secret: 351cef9ce60e980850221454b1319d79461c0ad358532e210842d8c2698fb5ed3844579aa7325c1d22c6efb6915836078ef19ca41dc56b244f1175777bcccc45

# Jasypt Configuration
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    password: 351cef9ce60e980850221454b1319d79461c0ad358532e210842d8c2698fb5ed3844579aa7325c1d22c6efb6915836078ef19ca41dc56b244f1175777bcccc45

#tmdb
tmdb:
  api:
    key: 30061af77dba3722bbe14a2691055544

#Swagger
springdoc:
  api-docs:
    path: /api/dbworld-api-doc
  swagger-ui:
    path: /dbworld-api-doc.html

dbworld:
  paths:
    tempDownloadPath: /ext_hdisk/dbworld/download/
    logFilePath: /app/db_world/logs/dbworld.log
    log4j2LogPath: /app/db_world/logs
    streamHomePath: /ext_hdisk/videos
    externalStreamHomePath: /home/dbworld_admin/ext_hdisk_1/videos
    torrentDownloadPath: /ext_hdisk/videos/Torrent Download
    ytdlpPath: yt-dlp
    hsCookiesPath: /home/dbworld_admin/ext_hdisk/dbworld/HS_COOKIES.txt
    extHDiskPath: /ext_hdisk

logging:
  config: classpath:log4j2.xml
