spring:
  config:
    activate:
      on-profile: prod


app:
  paths:
    base: /app/db_world
    data: /ext_hdisk/dbworld
    stream: /ext_hdisk/videos
    symlink: /ext_hdisk/video_symlink
    integration: ${app.paths.data}/integration
    external-videos: /home/dbworld_admin/ext_hdisk_1/videos

  tools:
    seven-zip: 7z
    mediainfo: mediainfo

server:
  port: ${SERVER_PORT:9090}

cors:
  allowed-origins: https://db-world.in

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    com.db.dbworld: INFO