# Server Config
Server:
  port: 9090
  jetty:
    idle-timeout: 60000 # 60 seconds

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12121212
    url: jdbc:mysql://dbworldpi:3306/db_world?createDatabaseIfNotExist=true&jdbcCompliantTruncation=false
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    enable-complex-map-key-serialization: true
  servlet:
    multipart:
      enabled: true
  #live server
  devtools:
    livereload:
      enable: false
      port: 35720

#Swagger
springdoc:
  api-docs:
    path: /api/dbworld-api-doc
  swagger-ui:
    path: /dbworld-api-doc.html

#Security
jwt:
  token:
    validity: 36000000  # validity in milisec 10*60*60*1000 ~ 10hour
    secret: 351cef9ce60e980850221454b1319d79461c0ad358532e210842d8c2698fb5ed3844579aa7325c1d22c6efb6915836078ef19ca41dc56b244f1175777bcccc45

# Jasypt Configuration
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    password: 351cef9ce60e980850221454b1319d79461c0ad358532e210842d8c2698fb5ed3844579aa7325c1d22c6efb6915836078ef19ca41dc56b244f1175777bcccc45

tmdb:
  api:
    key: 30061af77dba3722bbe14a2691055544

dbworld:
  paths:
    tempDownloadPath: download/
    logFilePath: logs/dbworld.log
    streamHomePath: D:/Bhavya/Videos
    externalStreamHomePath: F:/Bhavya/Videos
    torrentDownloadPath: D:/Bhavya/Videos/Torrent Download
    ytdlpPath: C:/YTDLP/yt-dlp.exe
    hsCookiesPath: D:\\Bhavya\\StartUp_Scripts\\Deployed\\cookies\\HS_COOKIES.txt
    extHDiskPath: /D:/Bhavya